### ISSUE TITLE
Add Edit and Delete Button and Refractor

### ISSUE THREAD

**Issue by viettrung2103** [viettrung2103/todoFlask#6]
*User Story: As a user, I can edit individual task, change name or description of the task or mark if the task is done or not.In addition, I can delete the task whether it is done or not*
- [x] **Add Edit Button and Delete Button (1h) 2h**
- [x] **Add Business Logic and route Logic concerning with edit and delete(1h) 2h**
- [ ] **Probably need to refractory by slicing if some logic might be used by other components(1h)**
- [ ] **Add gitignore, configure session, add static file **

**Comment by stenvma81** [comment]
Since there is no PR yet, I'm writing my comments here. Starting from general stuff...

What is are your thoughts behind the ***branch naming***? Dev 6 doesn't tell much to me but I kinda want to know what it is you are after here.

***Commit messages*** are clean, but very short. I'm not quite sure where these commits sit in the big picture. As the structure of your project is evolving, it would be nice if all commits, branch names etc. are somehow linked to the whole.

The amount of changes per commit is quite manageable, something I am struggling with atm.

***The project structure*** is ok. You should update your .gitignore though as ***flask_sessions*** can contain secrets. You can also configure flask to use a folder outside of your project for storing session data. Also, adding folders for routes, static files etc. now rather than later will save on work time.

- ***App.py***: The changes to app.py are logical and clear. We are however getting to the territory of "too much" here. Routes to routes.py etc. would clear things up.
-***Schema***: Nice and clear.
-***index.html***: Works. When amount of content increases, move logical chunks to templates.
-***other html***: No problems here.

**Comment by viettrung2103** [comment]
Thank you for your comment.
1. I plan to make an official dev branch. However, like you said, it would be more sensible to make a branch with name according the User Story
2. To me, any changes relating db, or any features, each of these change should be committed. However, like you said, I should combine more changes into one commit so that it would not dillute my commit history.
3. I will write it down in my backlog so I will continue to do it in the future development.
4. To be honest, I am getting the feeling of it now, whenever I want to navigate between features, it kinds of hard at the moment. I will try to slice these routes and logics into their own places.

Note, I just add the PR linking to this Issues. please check it out

**Comment by stenvma81** [comment]
For point 2 the conventions of DX actually encourage to make _very_ atomic commands so my comment is more of my own habits.

I also understand it might not be very easy to adapt to using DX as a guideline. At least for me, some habits have become quite hard to change as I have a certain logic behind them. They are probably not so obvious to others but are closely linked on how I work with projects. In a way it's like trying to learn how to ride a normal bike after learning how to deal with a unicycle. It's not really hard but sure feels strange.
